### ISSUE TITLE
SPIKE: PHP code quality GitHub action fails on `main`

### ISSUE THREAD

**Issue by kadamwhite** [wikimedia/shiro-wordpress-theme#111]
<img width="721" alt="image" src="https://github.com/wikimedia/shiro-wordpress-theme/assets/442115/c3c3b088-20ea-4883-b84d-744669c8e01f">

PHP tests are successful on PRs, but not on `main`.

**Comment by rebekahmarkowitz** [comment]
@kadamwhite To take a quick look at complexity and follow up with whether we think this can be added to this sprint or needs to be put on hold for when we have more time.

**Comment by kadamwhite** [comment]
This is going to be pretty straightforward to solve. The way the action works currently, is that it tries to find the "merge base" (the point of the split) between `main` and the PR's branch — which makes sense for PRs, but doesn't make sense for the main branch itself.

We'd ideally want to keep the current action as-is for PRs, but run `phpcs .` with no include list on the `main` branch. We could do this either with some conditional logic in the script, or by creating a different action to separate linting the base branch from linting the PRs. Either way, it shouldn't be a lot of action code needed to fix this.

The _fastest_ way to fix this would be to remove the file include list entirely and run `phpcs .` on every PR. The downside of that is that it causes the PR action to take a little longer, but we could benchmark to see how much of an impact it is. Might not be enough seconds of saving to bother.

**Comment by kadamwhite** [comment]
Resolved in #130 and subsequent direct commits to `main`.
