### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by varnent** [wikimedia/shiro-wordpress-theme#62]
Test issue for ZenHub setup purposes.

**Comment by varnent** [comment]
@rebekahmarkowitz - let me know if you are seeing this in your ZenHub setup. I am seeing it on the boards which projects that have this repo - but just want to verify. ;p

**Comment by rebekahmarkowitz** [comment]
I see it!

**Comment by rebekahmarkowitz** [comment]
@varnent I take that back. When I clicked the link, it opened it in the shiro repo. I'm not seeing it on the HM ZenHub

**Comment by varnent** [comment]
*tears in eyes* awesome - closing since this.....theoretically works....
